### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ghost** [ruud00000/bwa-u3-jammming-prj#6]
Satisfactory 👍 

First of all, good job getting this project to work! It's a smooth experience to get started searching for songs, adding them to playlists and finally adding those playlists to my actual Spotify account. You've also written your code very, very cleanly, making it easy to read. This was no small feat, good job!

Make sure you go back and fix the `addTrack()` function so that you prevent your users from spamming their own playlists! Also, get into the habit of treating `this.state` as immutable – it should *not* be edited directly. Create a new array or object and then pass that to setState as an argument.

**Comment by ruud00000** [comment]
tx
